// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgresql

import (
	"database/sql"

	"github.com/google/uuid"
)

type AppMovie struct {
	ID          uuid.UUID      `json:"id"`
	Title       string         `json:"title"`
	Description string         `json:"description"`
	KpRating    sql.NullString `json:"kp_rating"`
	ImdbRating  sql.NullString `json:"imdb_rating"`
	KpID        sql.NullInt32  `json:"kp_id"`
	Year        int32          `json:"year"`
	PosterPath  string         `json:"poster_path"`
	Country     string         `json:"country"`
	ReviewCount sql.NullInt32  `json:"review_count"`
}
