// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgresql

import (
	"database/sql"

	"github.com/google/uuid"
)

type AppUser struct {
	ID       uuid.UUID      `json:"id"`
	Username string         `json:"username"`
	Email    string         `json:"email"`
	PwdHash  string         `json:"pwd_hash"`
	Token    sql.NullString `json:"token"`
	Avatar   sql.NullString `json:"avatar"`
}
