// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/Watch2Gather/server/cmd/movie/config"
	"github.com/Watch2Gather/server/internal/movie/app/router"
	"github.com/Watch2Gather/server/internal/movie/infras/repo"
	"github.com/Watch2Gather/server/internal/movie/usecases/movies"
	"github.com/Watch2Gather/server/pkg/postgres"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func InitApp(cfg *config.Config, dbConnStr postgres.DBConnString, grpcServer *grpc.Server) (*App, func(), error) {
	dbEngine, cleanup, err := dbEngineFunc(dbConnStr)
	if err != nil {
		return nil, nil, err
	}
	movieRepo := repo.NewMovieRepo(dbEngine)
	useCase := movies.NewUseCase(movieRepo)
	movieServiceServer := router.NewGRPCMovieServer(grpcServer, cfg, useCase)
	app := New(cfg, dbEngine, useCase, movieServiceServer)
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

func dbEngineFunc(url postgres.DBConnString) (postgres.DBEngine, func(), error) {
	db, err := postgres.NewPostgresDB(url)
	if err != nil {
		return nil, nil, err
	}
	return db, func() { db.Close() }, nil
}
