app:
  name: "room-service"
  version: "1.0.0"

http:
  host: "0.0.0.0"
  port: 5003

postgres:
  pool_max: 2
  dsn_url: host=127.0.0.1 user=postgres password=password dbname=watch2gather sslmode=disable

logger:
  log_level: "debug"
