app:
  name: "reverse-proxy"
  version: "1.0.0"

http:
  host: "192.168.1.66"
  port: 8080

grpc:
  user_host: "0.0.0.0"
  user_port: 5002
  room_host: "0.0.0.0"
  room_port: 5003
  movie_host: "0.0.0.0"
  movie_port: 5004


log:
  log_level: "debug"
